El objetivo de este código es poder adquirir el conocimiento en python, para trasladar todo lo que sé de matlab 
a este lenguaje de programación.

## Puntos a tratar:
- ### Librerías más utilizadas
- ### Funciones típicas
- ### ¿Qué cosas sé hacer en matlab?
- ### Traslado de programas a python

## Librerías:

Para comenzar utilizaré 2 principales: Numpy y matplotlib

In [4]:
import numpy as np
import matplotlib.pyplot as plt

Para crear vectores se hace uso de la función np.array( ), donde todo el arreglo debe ir entre [ ]. Si se añade más de una fila, simplemente se agregan separadas por una coma:

In [11]:
matriz=np.array([[1,3,4],[2,0,1],[1,4,2]])
print(matriz)

[[1 3 4]
 [2 0 1]
 [1 4 2]]


Para referirse a los elementos del arreglo, se usan índices entre [ ], y van indexados desde 0 a n-1. En este caso la matriz tiene dimensión 3x3:

In [13]:
matriz[2,1]

4

Esto muestra el elemento de la fila 3 (índice 2) y columna 2 (índice 1).

## find en Python
En matlab, la función find, permite encontrar los índices de un arreglo que cumple cierta condición. 
En python la función que logra esto es "where". 

In [16]:
a,b=np.where(matriz<=1)
print(a,b)

[0 1 1 2] [0 1 2 0]
[1 0 1 1]


Los índices de "a" son las filas y "b" las columnas, en las cuales existía un número menor o igual a 1.

## encontrar -9999 y reemplazarlos por NaN

In [28]:

data=np.array([1,3,5,-9999,1,4,2,-9999,2,1,4,0,0,-9999],dtype=float)
idx=np.where(data==-9999)
print(idx)
data[idx]=np.nan
print(data)

(array([ 3,  7, 13]),)
[ 1.  3.  5. nan  1.  4.  2. nan  2.  1.  4.  0.  0. nan]


Notar que se define "data" de tipo flotante, ya que "np.nan" es un valor flotante. 
